export const stationData = {
  Fac_IDNumber: "105457-5",
  Name: "ETEST",
  Comm_FacName: "ETEST HEALTH CENTRE ",
  Zone: "Western",
  Region_Code: "TZ.WT.TB",
  Region: "Tabora",
  District_Code: "TZ.WT.TB.TB",
  District: "Tabora",
  Council_Code: "TZ.WT.TB.",
  Council: "Tabora MC",
  Ward: "Chemchem",
  Village: "Sikanda",
  Village_Code: "TZ.WT.TB.TB.6.4.1",
  FacilityTypeGroupCode: "HLCTR",
  FacilityTypeGroup: "Health Center",
  FacilityTypeCode: "HLCTR",
  FacilityType: "Health Center", //
  OwnershipGroupCode: "Priv",
  OwnershipGroup: "Private",
  OwnershipCode: "comp",
  Ownership: "Company/Business Name", //
  OperatingStatus: "Operating", //
  Latitude: "-5.02576",
  Longitude: "32.79645",
  RegistrationStatus: "Registered",
  OpenedDate: "2024-05-27 00:00:00",
  CreatedAt: "2024-05-30 00:00:00",
  UpdatedAt: "2024-05-30 11:20:23",
  Vote: "TZ.WT.TB.TB.6",
  IsDesignated: 0,
  ClosedDate: "",
  OSchangeOpenedtoClose: "N",
  OSchangeClosedtoOperational: "N",
  PostorUpdate: "U",
};

export const displayData = [
  {
    Fac_IDNumber: "105457-5",
    Name: "ETEST",
    Region: "Tabora",
    District: "Tabora",
    OpenedDate: "2024-05-27 00:00:00",
    CreatedAt: "2024-05-30 00:00:00",
    FacilityType: "Health Center",
    Ownership: "Company/Business Name",
    OperatingStatus: "Operating",
  },
];
